# Starship Configuration
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

# Configure the format of the prompt
format = """
[╭─](bold green)$all$character"""

right_format = """$time"""

# Configure the continuation prompt
continuation_prompt = "[╰─](bold green)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[➜](bold yellow)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[nodejs]
symbol = " "
style = "bold green"

[python]
symbol = " "
style = "bold blue"

[rust]
symbol = " "
style = "bold orange"

[docker_context]
symbol = " "
style = "bold blue"

[package]
symbol = " "
style = "bold yellow"

[memory_usage]
disabled = false
threshold = 70
symbol = " "
style = "bold dimmed red"

[time]
disabled = false
format = '🕙 [$time]($style) '
style = "bold yellow"
time_format = "%R"

[username]
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold red) "
disabled = false

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow)"

[jobs]
symbol = "✦"
style = "bold blue"
number_threshold = 1
format = "[$symbol$number]($style) "

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[status]
style = "bold red"
symbol = "✖"
format = '[$symbol $common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 " 
